version: '2.3'
services:
  bot:
    image: ghcr.io/erisa/lykos
    env_file: .env
    restart: on-failure
    volumes:
      - type: bind
        source: ./src/config.json
        target: /app/config.json
        #Windows
        #source: ./config
        #target: C:/app/config
 # redis:
 #   image: redis:alpine
 #   volumes:
 #     - type: bind
 #       source: ./data
 #       target: /data
