version: '2.3'
services:
  bot:
    image: ghcr.io/erisa/lykos
    restart: on-failure
    volumes:
      - type: bind
        source: ./src/config.json
        target: /app/config.json
        #Windows
        #source: ./config
        #target: C:/app/config
  redis:
    image: redis:alpiine
    volumes:
      - type: bind
        source: ./data
        target: /data
