# fly.toml app configuration file generated for lykos on 2023-04-20T21:48:12+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lykos"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = 5

[experimental]
  auto_rollback = true

[deploy]
  strategy = "rolling"
