global using DSharpPlus;
global using DSharpPlus.CommandsNext;
global using DSharpPlus.CommandsNext.Attributes;
global using DSharpPlus.CommandsNext.Exceptions;
global using DSharpPlus.Entities;
global using DSharpPlus.EventArgs;
global using DSharpPlus.SlashCommands;
global using Lykos.Modules;
global using Microsoft.Extensions.Logging;
global using Minio;
global using Minio.Exceptions;
global using Newtonsoft.Json;
global using StackExchange.Redis;
global using System;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
global using System.Net;
global using System.Net.Http;
global using System.Runtime.InteropServices;
global using System.Security.Cryptography;
global using System.Text;
global using System.Text.RegularExpressions;
global using System.Threading.Tasks;
global using Microsoft.Extensions.Configuration;
global using static Lykos.Config;
global using static Lykos.Modules.Helpers;