name: .NET Core (Standalone build)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-standalone:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
